SELECT CONCAT('/home/grep/src/',F.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM (SELECT BOARD_ID
      FROM USED_GOODS_BOARD
      ORDER BY VIEWS DESC
      LIMIT 1)  AS B
JOIN USED_GOODS_FILE AS F
ON F.BOARD_ID=B.BOARD_ID
ORDER BY F.FILE_ID DESC